version: "3.8"

services:
  jet-telegram-bot:
    container_name: jet-telegram-bot
    hostname: jet-telegram-bot
    image: registry.trak.spb.ru/jet-movie-top-bot:latest
    restart: always
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - KINOPOISK_TOKEN=${KINOPOISK_TOKEN}
      - TELEGRAM_BOT_NAME=${TELEGRAM_BOT_NAME}
    volumes:
      - /home/app/:/usr/local/var/db/
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s
